name: atac_chip_preprocess
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _r-mutex=1.0.1
  - bedtools=2.30.0
  - bowtie2=2.4.4
  - bwidget=1.9.14
  - bzip2=1.0.8
  - c-ares=1.17.1
  - ca-certificates=2021.7.5
  - cairo=1.16.0
  - certifi=2021.5.30
  - curl=7.77.0
  - cutadapt=3.4
  - dnaio=0.5.1
  - fastqc=0.11.9
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.13.1
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.10.4
  - fribidi=1.0.10
  - genrich=0.6.1
  - gettext=0.21.0
  - giflib=5.2.1
  - graphite2=1.3.14
  - gsl=2.6
  - harfbuzz=2.8.2
  - htslib=1.13
  - icu=68.1
  - isa-l=2.30.0
  - jpeg=9d
  - krb5=1.19.1
  - lcms2=2.12
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=7.77.0
  - libdeflate=1.7
  - libedit=3.1.20210216
  - libev=4.33
  - libffi=3.3
  - libglib=2.68.3
  - libiconv=1.16
  - liblapack=3.9.0
  - libnghttp2=1.43.0
  - libopenblas=0.3.15
  - libpng=1.6.37
  - libssh2=1.9.0
  - libtiff=4.2.0
  - libuuid=2.32.1
  - libwebp-base=1.2.0
  - libxml2=2.9.12
  - lz4-c=1.9.3
  - macs2=2.2.7.1
  - make=4.3
  - mawk=1.3.4
  - multiqc=1.11
  - ncurses=6.2
  - numpy=1.21.1
  - openjdk=11.0.9.1
  - openssl=1.1.1k
  - pango=1.48.7
  - pcre=8.45
  - pcre2=10.36
  - perl=5.32.1
  - picard=2.25.7
  - pigz=2.6
  - pip=21.1.3
  - pixman=0.40.0
  - python=3.9.6
  - python-isal=0.10.0
  - python_abi=3.9
  - r-base=4.0.5
  - readline=8.1
  - samblaster=0.1.26
  - samtools=1.13
  - sed=4.8
  - setuptools=52.0.0
  - sqlite=3.36.0
  - subread=2.0.1
  - tbb=2020.3
  - tk=8.6.10
  - tktable=2.10
  - tzdata=2021a
  - wheel=0.36.2
  - xopen=1.1.0
  - xorg-fixesproto=5.0
  - xorg-inputproto=2.3.2
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.7.2
  - xorg-libxext=1.3.4
  - xorg-libxfixes=5.0.3
  - xorg-libxi=1.7.10
  - xorg-libxrender=0.9.10
  - xorg-libxt=1.2.1
  - xorg-libxtst=1.2.3
  - xorg-recordproto=1.14.2
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.4.9
