name: atac_chip_preprocess
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bedtools
  - bowtie2
  - fastp
  - fastqc
  - genrich
  - macs2
  - mawk
  - multiqc
  - picard
  - samblaster
  - sambamba
  - samtools
  - subread
  - tabix
  - ucsc-bedgraphtobigwig
  - ucsc-bigwigtobedgraph

  
