# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: 
      - dev
      - main
    paths-ignore:
      - README.md
      - .gitignore
      - versions_DockerHub.md
        
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      #/ borrowed from nf-core:
      - name: Install Nextflow
        run: |
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/
          
      - name: test_conda
        run: |
          NXF_VER=21.04.3 nextflow run main.nf -profile test_index,conda
          NXF_VER=21.04.3 nextflow run main.nf -profile test_paired,conda
          NXF_VER=21.04.3 nextflow run main.nf -profile test_single,conda
          NXF_VER=21.04.3 nextflow run main.nf -profile test_paired,conda --atacseq
          NXF_VER=21.04.3 nextflow run main.nf -profile test_single,conda --atacseq

      - name: test_docker
        run: |
          NXF_VER=21.04.3 nextflow run main.nf -profile test_index,docker
          NXF_VER=21.04.3 nextflow run main.nf -profile test_paired,docker
          NXF_VER=21.04.3 nextflow run main.nf -profile test_single,docker
          NXF_VER=21.04.3 nextflow run main.nf -profile test_paired,docker --atacseq
          NXF_VER=21.04.3 nextflow run main.nf -profile test_single,docker --atacseq
